---
name: Mirror Repository

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror Repository
        uses: 0xTheProDev/Gitlab-Mirror-Action@v1
        with:
          followTags: true
          password: ${{ secrets.GITLAB_PAT }}
          projectId: "distributed-lock"
          userName: "0xTheProDev"
