---
name: Mirror Repository

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror Repository
        uses: ./.github/shared/gitlab
        with:
          followTags: "true"
          password: ${{ secrets.GITLAB_PAT }}
          projectId: "distributed-lock"
          userName: "0xTheProDev"
